# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Advance Upstream Forks

on:
  schedule:
    # Every hour
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  advance_llvm-project:
    name: "Advance llvm-project"
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: shark-infra/llvm-project
          ref: main

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/llvm/llvm-project.git
          git pull --ff-only upstream main
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: main
          repository: shark-infra/llvm-project
